"""Auto-generated migration 20240823_104206

Revision ID: 02f5a8e437f4
Revises: 03af0dcbdf98
Create Date: 2024-08-23 10:42:07.193628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f5a8e437f4'
down_revision: Union[str, None] = '03af0dcbdf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
