"""Sync database after merge

Revision ID: 03af0dcbdf98
Revises: b0e573c7c114
Create Date: 2024-08-23 10:27:51.981286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03af0dcbdf98'
down_revision: Union[str, None] = 'b0e573c7c114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drawings_hash', table_name='drawings')
    op.drop_index('ix_drawings_id', table_name='drawings')
    # Сначала удаляем зависимость
    op.drop_constraint('order_drawings_drawing_id_fkey', 'order_drawings', type_='foreignkey')
    op.drop_table('drawings')
    op.drop_index('ix_order_drawings_id', table_name='order_drawings')
    op.drop_table('order_drawings')
    op.add_column('production_orders', sa.Column('drawing_link', sa.String(), nullable=True))
    op.add_column('production_orders', sa.Column('archived_drawings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'archived_drawings')
    op.drop_column('production_orders', 'drawing_link')
    op.create_table('order_drawings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drawing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qr_code_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], name='order_drawings_drawing_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], name='order_drawings_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_drawings_pkey')
    )
    op.create_index('ix_order_drawings_id', 'order_drawings', ['id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='drawings_pkey')
    )
    op.create_foreign_key('order_drawings_drawing_id_fkey', 'order_drawings', 'drawings', ['drawing_id'], ['id'])
    op.create_index('ix_drawings_id', 'drawings', ['id'], unique=False)
    op.create_index('ix_drawings_hash', 'drawings', ['hash'], unique=True)
    # ### end Alembic commands ###
