"""Auto-generated migration 20240814_094127

Revision ID: 06fcc36d480d
Revises: 8ffa23423623
Create Date: 2024-08-14 09:41:27.450851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fcc36d480d'
down_revision: Union[str, None] = '8ffa23423623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
