"""Auto-generated migration 20240905_094018

Revision ID: 0c89e26664d6
Revises: 8f73278b9773
Create Date: 2024-09-05 09:40:18.691657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c89e26664d6'
down_revision: Union[str, None] = '8f73278b9773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
