"""Auto-generated migration 20240806_144741

Revision ID: 0cbd2173c697
Revises: d4ede09ac124
Create Date: 2024-08-06 14:47:41.743650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbd2173c697'
down_revision: Union[str, None] = 'd4ede09ac124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
