"""Auto-generated migration 20241009_103246

Revision ID: 0d0eeb0e2a8f
Revises: 825837d6be6d
Create Date: 2024-10-09 10:32:46.974753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0eeb0e2a8f'
down_revision: Union[str, None] = '825837d6be6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
