"""Auto-generated migration 20241025_122613

Revision ID: 10af5598aad0
Revises: 8f307de16d9b
Create Date: 2024-10-25 12:26:14.184313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10af5598aad0'
down_revision: Union[str, None] = '8f307de16d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
