"""add_revoked_tokens_table

Revision ID: 120adbb4b6d0
Revises: f4f2d27bab51
Create Date: 2024-10-24 14:30:40.187636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120adbb4b6d0'
down_revision: Union[str, None] = 'f4f2d27bab51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
