"""Auto-generated migration 20241007_134827

Revision ID: 12af1d58cf47
Revises: 3e26d092b5e9
Create Date: 2024-10-07 13:48:27.887573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12af1d58cf47'
down_revision: Union[str, None] = '3e26d092b5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
