"""Auto-generated migration 20240905_130441

Revision ID: 12d738893036
Revises: ea2cd6f80cdb
Create Date: 2024-09-05 13:04:42.396729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d738893036'
down_revision: Union[str, None] = 'ea2cd6f80cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
