"""Auto-generated migration 20241108_133922

Revision ID: 13324409a3e5
Revises: dca28236e586
Create Date: 2024-11-08 13:39:22.664218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13324409a3e5'
down_revision: Union[str, None] = 'dca28236e586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
