"""Auto-generated migration 20241007_131608

Revision ID: 14838ac86f42
Revises: ebacd2c1eb97
Create Date: 2024-10-07 13:16:09.483834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14838ac86f42'
down_revision: Union[str, None] = 'ebacd2c1eb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
