"""Add an is_deleted field for 'Soft Delete'

Revision ID: 173f0493b11b
Revises: 77b1639d2117
Create Date: 2024-10-16 12:29:37.890578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173f0493b11b'
down_revision: Union[str, None] = '77b1639d2117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_production_orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('archived_work_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('production_orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('work_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_logs', 'is_deleted')
    op.drop_column('production_orders', 'is_deleted')
    op.drop_column('archived_work_logs', 'is_deleted')
    op.drop_column('archived_production_orders', 'is_deleted')
    # ### end Alembic commands ###
