"""Auto-generated migration 20241102_121926

Revision ID: 195d6306a38e
Revises: 2c4482fb4bb1
Create Date: 2024-11-02 12:19:27.109643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195d6306a38e'
down_revision: Union[str, None] = '2c4482fb4bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_sessions_expired_at', 'user_sessions', ['expired_at'], unique=False)
    op.create_index('idx_user_sessions_last_activity', 'user_sessions', ['last_activity'], unique=False)
    op.create_index('idx_user_sessions_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_sessions_user_active', table_name='user_sessions')
    op.drop_index('idx_user_sessions_last_activity', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expired_at', table_name='user_sessions')
    # ### end Alembic commands ###
