"""Auto-generated migration 20241023_094918

Revision ID: 1f3bf23549c7
Revises: f7888e2677da
Create Date: 2024-10-23 09:49:18.864459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3bf23549c7'
down_revision: Union[str, None] = 'f7888e2677da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
