"""Auto-generated migration 20240826_141311

Revision ID: 21383d6699f9
Revises: d220eaa27e41
Create Date: 2024-08-26 14:13:12.313339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21383d6699f9'
down_revision: Union[str, None] = 'd220eaa27e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
