"""Auto-generated migration 20240917_101838

Revision ID: 26881dbe1c75
Revises: f2cb2c1d2206
Create Date: 2024-09-17 10:18:39.017777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26881dbe1c75'
down_revision: Union[str, None] = 'f2cb2c1d2206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
