"""Auto-generated migration 20240826_140327

Revision ID: 2bab438f360d
Revises: 493b7af2b0b3
Create Date: 2024-08-26 14:03:27.925735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bab438f360d'
down_revision: Union[str, None] = '493b7af2b0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
