"""Auto-generated migration 20240815_151146

Revision ID: 2f788ddd09ab
Revises: 7e247b3ab446
Create Date: 2024-08-15 15:11:46.445672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f788ddd09ab'
down_revision: Union[str, None] = '7e247b3ab446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
