"""Добавил class RefreshTokenRequest(BaseModel)

Revision ID: 36f20320985f
Revises: 13324409a3e5
Create Date: 2024-11-29 09:01:38.088639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f20320985f'
down_revision: Union[str, None] = '13324409a3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
