"""Auto-generated migration 20240805_145538

Revision ID: 3b75a42a22f4
Revises: 4f372bac756f
Create Date: 2024-08-05 14:55:39.320256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b75a42a22f4'
down_revision: Union[str, None] = '4f372bac756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
