"""Auto-generated migration 20240826_101408

Revision ID: 3cb1e4d12ff4
Revises: 02f5a8e437f4
Create Date: 2024-08-26 10:14:09.372682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb1e4d12ff4'
down_revision: Union[str, None] = '02f5a8e437f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
