"""Добавил DateTime для UserSession

Revision ID: 3e35231bccd5
Revises: e1fe9b1034a6
Create Date: 2024-11-02 11:44:02.836679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e35231bccd5'
down_revision: Union[str, None] = 'e1fe9b1034a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_token_type', table_name='revoked_tokens')
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_revoked_tokens_token_type', 'revoked_tokens', ['token_type'], unique=False)
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
