"""Auto-generated migration 20241010_095852

Revision ID: 42288fbbc30a
Revises: 772fd30235fd
Create Date: 2024-10-10 09:58:52.628085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42288fbbc30a'
down_revision: Union[str, None] = '772fd30235fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
