"""Auto-generated migration 20241024_143419

Revision ID: 43893d4fab89
Revises: 120adbb4b6d0
Create Date: 2024-10-24 14:34:19.948553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43893d4fab89'
down_revision: Union[str, None] = '120adbb4b6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
