"""Auto-generated migration 20241009_135411

Revision ID: 455d1532dbea
Revises: a9679d98532c
Create Date: 2024-10-09 13:54:12.015982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455d1532dbea'
down_revision: Union[str, None] = 'a9679d98532c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
