"""Auto-generated migration 20241022_102928

Revision ID: 46422871dfbe
Revises: a17a9590fc32
Create Date: 2024-10-22 10:29:29.584644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46422871dfbe'
down_revision: Union[str, None] = 'a17a9590fc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
