"""Auto-generated migration 20241023_110202

Revision ID: 47a263ca8cb1
Revises: 1f3bf23549c7
Create Date: 2024-10-23 11:02:02.835516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a263ca8cb1'
down_revision: Union[str, None] = '1f3bf23549c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
