"""Add publication_date to ProductionOrder

Revision ID: 48c4294f2034
Revises: 9a1434f9fc6e
Create Date: 2024-07-23 14:43:02.497198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c4294f2034'
down_revision: Union[str, None] = '9a1434f9fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('publication_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'publication_date')
    # ### end Alembic commands ###
