"""Auto-generated migration 20240805_140226

Revision ID: 4f372bac756f
Revises: a38f2db72c71
Create Date: 2024-08-05 14:02:27.401286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f372bac756f'
down_revision: Union[str, None] = 'a38f2db72c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drawings_id', table_name='drawings')
    op.drop_table('drawings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('drawing_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], name='drawings_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='drawings_pkey')
    )
    op.create_index('ix_drawings_id', 'drawings', ['id'], unique=False)
    # ### end Alembic commands ###
