"""Auto-generated migration 20241009_142729

Revision ID: 5419814bfbd0
Revises: 455d1532dbea
Create Date: 2024-10-09 14:27:29.893288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5419814bfbd0'
down_revision: Union[str, None] = '455d1532dbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
