"""Auto-generated migration 20241023_131747

Revision ID: 55a3979542ce
Revises: 47a263ca8cb1
Create Date: 2024-10-23 13:17:48.520923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a3979542ce'
down_revision: Union[str, None] = '47a263ca8cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
