"""Auto-generated migration 20240826_101940

Revision ID: 594c95818d1d
Revises: 3cb1e4d12ff4
Create Date: 2024-08-26 10:19:40.624009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594c95818d1d'
down_revision: Union[str, None] = '3cb1e4d12ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
