"""Auto-generated migration 20240916_143528

Revision ID: 59cfca4d9374
Revises: ae0103219d20
Create Date: 2024-09-16 14:35:29.208021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cfca4d9374'
down_revision: Union[str, None] = 'ae0103219d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
