"""Auto-generated migration 20241029_144426

Revision ID: 5eb47b324a93
Revises: ca43ea88a806
Create Date: 2024-10-29 14:44:27.361014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb47b324a93'
down_revision: Union[str, None] = 'ca43ea88a806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
