"""Auto-generated migration 20240826_133322

Revision ID: 5edde1a1056e
Revises: fe3b12be5343
Create Date: 2024-08-26 13:33:22.937270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edde1a1056e'
down_revision: Union[str, None] = 'fe3b12be5343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
