"""Auto-generated migration 20240815_125140

Revision ID: 609cec530f87
Revises: 8c72474cec0f
Create Date: 2024-08-15 12:51:41.085914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609cec530f87'
down_revision: Union[str, None] = '8c72474cec0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
