"""Auto-generated migration 20240919_131833

Revision ID: 62182b007731
Revises: b0836ca7ca75
Create Date: 2024-09-19 13:18:33.678314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62182b007731'
down_revision: Union[str, None] = 'b0836ca7ca75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
