"""Добавил очистку старых сессий

Revision ID: 64861b00a455
Revises: 43893d4fab89
Create Date: 2024-10-25 09:51:37.850562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64861b00a455'
down_revision: Union[str, None] = '43893d4fab89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('cleanup_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'cleanup_reason')
    op.drop_column('user_sessions', 'expired_at')
    # ### end Alembic commands ###
