"""Auto-generated migration 20241021_095617

Revision ID: 648ecafae217
Revises: 8794c0b00885
Create Date: 2024-10-21 09:56:18.003757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648ecafae217'
down_revision: Union[str, None] = '8794c0b00885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
