"""current_database_state

Revision ID: 65a677c50224
Revises: aa03f5e92c32
Create Date: 2024-09-19 14:37:10.411729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a677c50224'
down_revision: Union[str, None] = 'aa03f5e92c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_drawings', 'qr_code_path')
    op.add_column('production_orders', sa.Column('qr_code_path', sa.String(length=255), nullable=True))
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('production_orders', 'qr_code_path')
    op.add_column('order_drawings', sa.Column('qr_code_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
