"""Auto-generated migration 20240827_133434

Revision ID: 6b3422cfa9db
Revises: 833565f12ada
Create Date: 2024-08-27 13:34:34.775294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3422cfa9db'
down_revision: Union[str, None] = '833565f12ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
