"""Auto-generated migration 20240827_123912

Revision ID: 6ba2140a5f98
Revises: b86bdc0dab83
Create Date: 2024-08-27 12:39:12.534293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba2140a5f98'
down_revision: Union[str, None] = 'b86bdc0dab83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
