"""Update metal_delivery_date to FlexibleDate

Revision ID: 6dc2630c301b
Revises: 988b3251d2e9
Create Date: 2024-07-18 14:14:06.239031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc2630c301b'
down_revision: Union[str, None] = '988b3251d2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
