"""Auto-generated migration 20241211_125009

Revision ID: 72b2ef5cb09b
Revises: dbfc8a4a2464
Create Date: 2024-12-11 12:50:10.574757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b2ef5cb09b'
down_revision: Union[str, None] = 'dbfc8a4a2464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
