"""Auto-generated migration 20241010_090852

Revision ID: 772fd30235fd
Revises: 5419814bfbd0
Create Date: 2024-10-10 09:08:53.120135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772fd30235fd'
down_revision: Union[str, None] = '5419814bfbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
