"""Auto-generated migration 20241025_135945

Revision ID: 7964bb238fa5
Revises: 10af5598aad0
Create Date: 2024-10-25 13:59:46.256585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7964bb238fa5'
down_revision: Union[str, None] = '10af5598aad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
