"""Auto-generated migration 20241007_101815

Revision ID: 79af3bfd43af
Revises: fb0c7b85c22a
Create Date: 2024-10-07 10:18:15.787155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79af3bfd43af'
down_revision: Union[str, None] = 'fb0c7b85c22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
