"""Auto-generated migration 20241008_143559

Revision ID: 825837d6be6d
Revises: 992f77bd083c
Create Date: 2024-10-08 14:36:00.577215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825837d6be6d'
down_revision: Union[str, None] = '992f77bd083c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
