"""Новое поле для архивированных чертежей

Revision ID: 86125ac7ab4c
Revises: aa80be8cf908
Create Date: 2024-08-15 10:35:10.392892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86125ac7ab4c'
down_revision: Union[str, None] = 'aa80be8cf908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('archived_drawings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'archived_drawings')
    # ### end Alembic commands ###
