"""Add OTP field to User

Revision ID: 8794c0b00885
Revises: 173f0493b11b
Create Date: 2024-10-21 09:03:22.491768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8794c0b00885'
down_revision: Union[str, None] = '173f0493b11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
