"""Auto-generated migration 20240920_122030

Revision ID: 890dc02d87fa
Revises: 62182b007731
Create Date: 2024-09-20 12:20:31.145197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890dc02d87fa'
down_revision: Union[str, None] = '62182b007731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
