"""Auto-generated migration 20240815_115933

Revision ID: 8c72474cec0f
Revises: 86125ac7ab4c
Create Date: 2024-08-15 11:59:34.144972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c72474cec0f'
down_revision: Union[str, None] = '86125ac7ab4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
