"""Auto-generated migration 20240806_133039

Revision ID: 8cb7c43eea97
Revises: a1cbedf104a8
Create Date: 2024-08-06 13:30:40.186381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb7c43eea97'
down_revision: Union[str, None] = 'a1cbedf104a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
