"""Добавил get_active_sessions_count

Revision ID: 8f307de16d9b
Revises: c5c0845c70fc
Create Date: 2024-10-25 11:51:08.492631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f307de16d9b'
down_revision: Union[str, None] = 'c5c0845c70fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
