"""Auto-generated migration 20240812_132821

Revision ID: 8ffa23423623
Revises: f996dbc7d541
Create Date: 2024-08-12 13:28:21.464280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffa23423623'
down_revision: Union[str, None] = 'f996dbc7d541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
