"""Auto-generated migration 20240919_122034

Revision ID: 928a76418482
Revises: 39dfb9dfed07
Create Date: 2024-09-19 12:20:35.153342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928a76418482'
down_revision: Union[str, None] = '39dfb9dfed07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
