"""Change metal_delivery_date to String

Revision ID: 992f77bd083c
Revises: e071d0338bcd
Create Date: 2024-10-08 14:33:53.978094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992f77bd083c'
down_revision: Union[str, None] = 'e071d0338bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archived_production_orders', 'metal_delivery_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('production_orders', 'metal_delivery_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'metal_delivery_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('archived_production_orders', 'metal_delivery_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
