"""Auto-generated migration 20241022_132618

Revision ID: 9b35c30f62c0
Revises: 60a610ffe7cd
Create Date: 2024-10-22 13:26:18.697927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b35c30f62c0'
down_revision: Union[str, None] = '60a610ffe7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
