"""Auto-generated migration 20240809_105826

Revision ID: 9d20844eb9b4
Revises: 0cbd2173c697
Create Date: 2024-08-09 10:58:28.192075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d20844eb9b4'
down_revision: Union[str, None] = '0cbd2173c697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
