"""Auto-generated migration 20240816_085543

Revision ID: 9efee59ad648
Revises: 2f788ddd09ab
Create Date: 2024-08-16 08:55:43.778750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efee59ad648'
down_revision: Union[str, None] = '2f788ddd09ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
