"""Auto-generated migration 20240806_130611

Revision ID: a1cbedf104a8
Revises: b7cc50e12b36
Create Date: 2024-08-06 13:06:11.545694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cbedf104a8'
down_revision: Union[str, None] = 'b7cc50e12b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
