"""Update ProductionOrder model

Revision ID: a38f2db72c71
Revises: 48c4294f2034
Create Date: 2024-07-30 13:15:55.049802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38f2db72c71'
down_revision: Union[str, None] = '48c4294f2034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
