"""Auto-generated migration 20241022_140006

Revision ID: a536411a9f46
Revises: dea361cf801e
Create Date: 2024-10-22 14:00:06.784355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a536411a9f46'
down_revision: Union[str, None] = 'dea361cf801e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
