"""Auto-generated migration 20240918_142346

Revision ID: a74c0bf65b90
Revises: 7e0632ab7fa4
Create Date: 2024-09-18 14:23:46.882523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74c0bf65b90'
down_revision: Union[str, None] = '7e0632ab7fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
