"""Auto-generated migration 20241009_121417

Revision ID: a9679d98532c
Revises: f30ddc4ccd6d
Create Date: 2024-10-09 12:14:18.073554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9679d98532c'
down_revision: Union[str, None] = 'f30ddc4ccd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
