"""Auto-generated migration 20240826_102057

Revision ID: aa5d7a8933ea
Revises: 594c95818d1d
Create Date: 2024-08-26 10:20:58.261972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5d7a8933ea'
down_revision: Union[str, None] = '594c95818d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
