"""Auto-generated migration 20240815_100617

Revision ID: aa80be8cf908
Revises: 4fe103c285a8
Create Date: 2024-08-15 10:06:17.815906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa80be8cf908'
down_revision: Union[str, None] = '4fe103c285a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
