"""Auto-generated migration 20240816_124515

Revision ID: af82557046ac
Revises: 9efee59ad648
Create Date: 2024-08-16 12:45:15.967968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af82557046ac'
down_revision: Union[str, None] = '9efee59ad648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
