"""Auto-generated migration 20240919_131342

Revision ID: b0836ca7ca75
Revises: 928a76418482
Create Date: 2024-09-19 13:13:43.342827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0836ca7ca75'
down_revision: Union[str, None] = '928a76418482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
