"""Оптимизация schemas.py и database.py

Revision ID: b2b12df59ec1
Revises: 72b2ef5cb09b
Create Date: 2024-12-17 14:12:30.530910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b12df59ec1'
down_revision: Union[str, None] = '72b2ef5cb09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
