"""Add archiving functionality

Revision ID: b5330111209d
Revises: 9408612bca42
Create Date: 2024-10-04 14:33:09.952265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5330111209d'
down_revision: Union[str, None] = 'fb54935d2e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE IF NOT EXISTS shift AS ENUM ('DAY', 'NIGHT')")
    op.create_table('archived_production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('desired_production_date_start', sa.Date(), nullable=False),
    sa.Column('desired_production_date_end', sa.Date(), nullable=False),
    sa.Column('required_material', sa.String(length=100), nullable=False),
    sa.Column('metal_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('drawing_link', sa.String(length=255), nullable=True),
    sa.Column('archived_drawings', sa.String(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_production_orders_id'), 'archived_production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_archived_production_orders_order_number'), 'archived_production_orders', ['order_number'], unique=True)
    op.create_table('archived_work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('operation_time', sa.Integer(), nullable=False),
    sa.Column('adjuster_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_work_logs_id'), 'archived_work_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_work_logs_id'), table_name='archived_work_logs')
    op.drop_table('archived_work_logs')
    op.drop_index(op.f('ix_archived_production_orders_order_number'), table_name='archived_production_orders')
    op.drop_index(op.f('ix_archived_production_orders_id'), table_name='archived_production_orders')
    op.drop_table('archived_production_orders')
    op.execute("DROP TYPE IF EXISTS shift")
    # ### end Alembic commands ###
