"""Auto-generated migration 20240806_101913

Revision ID: b7cc50e12b36
Revises: 3b75a42a22f4
Create Date: 2024-08-06 10:19:14.114376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cc50e12b36'
down_revision: Union[str, None] = '3b75a42a22f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
