"""Auto-generated migration 20241025_140912

Revision ID: c1921ed6b9e1
Revises: cdc9090a42e4
Create Date: 2024-10-25 14:09:13.233184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1921ed6b9e1'
down_revision: Union[str, None] = 'cdc9090a42e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
