"""Auto-generated migration 20240905_105036

Revision ID: cd11aac03823
Revises: 0c89e26664d6
Create Date: 2024-09-05 10:50:36.812742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd11aac03823'
down_revision: Union[str, None] = '0c89e26664d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
