"""Auto-generated migration 20241025_140455

Revision ID: cdc9090a42e4
Revises: 7964bb238fa5
Create Date: 2024-10-25 14:04:56.505850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc9090a42e4'
down_revision: Union[str, None] = '7964bb238fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
