"""Add archiving functionality

Revision ID: d04a625f395c
Revises: 41153c4da03a
Create Date: 2024-10-07 10:08:38.171277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04a625f395c'
down_revision: Union[str, None] = '41153c4da03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('desired_production_date_start', sa.Date(), nullable=False),
    sa.Column('desired_production_date_end', sa.Date(), nullable=False),
    sa.Column('required_material', sa.String(length=100), nullable=False),
    sa.Column('metal_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('drawing_link', sa.String(length=255), nullable=True),
    sa.Column('archived_drawings', sa.String(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_production_orders_id'), 'archived_production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_archived_production_orders_order_number'), 'archived_production_orders', ['order_number'], unique=True)
    op.create_table('archived_work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    # sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('operation_time', sa.Integer(), nullable=False),
    sa.Column('adjuster_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_work_logs_id'), 'archived_work_logs', ['id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_hash'), 'drawings', ['hash'], unique=True)
    op.create_index(op.f('ix_drawings_id'), 'drawings', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('desired_production_date_start', sa.Date(), nullable=False),
    sa.Column('desired_production_date_end', sa.Date(), nullable=False),
    sa.Column('required_material', sa.String(length=100), nullable=False),
    sa.Column('metal_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('drawing_link', sa.String(length=255), nullable=True),
    sa.Column('archived_drawings', sa.String(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('desired_production_date_end >= desired_production_date_start', name='check_date_range'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_table('order_drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_drawings_id'), 'order_drawings', ['id'], unique=False)
    op.create_index(op.f('ix_order_drawings_order_id'), 'order_drawings', ['order_id'], unique=False)
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    # sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('operation_time', sa.Integer(), nullable=False),
    sa.Column('adjuster_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.CheckConstraint('produced_quantity > 0', name='check_produced_quantity_positive'),
    sa.ForeignKeyConstraint(['adjuster_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_number'], ['production_orders.order_number'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)
    op.create_table('operation_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_log_id', sa.Integer(), nullable=False),
    sa.Column('next_operation_zinc', sa.Boolean(), nullable=False),
    sa.Column('next_operation_cnc', sa.Boolean(), nullable=False),
    sa.Column('parts_per_operation', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_log_id'], ['work_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_log_id')
    )
    op.create_index(op.f('ix_operation_details_id'), 'operation_details', ['id'], unique=False)
    op.create_table('setup_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_log_id', sa.Integer(), nullable=False),
    sa.Column('setup_start', sa.Time(), nullable=True),
    sa.Column('setup_end', sa.Time(), nullable=True),
    sa.Column('setups_count', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_log_id'], ['work_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_log_id')
    )
    op.create_index(op.f('ix_setup_info_id'), 'setup_info', ['id'], unique=False)
    op.create_table('work_log_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_log_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_log_id'], ['work_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_log_id')
    )
    op.create_index(op.f('ix_work_log_notes_id'), 'work_log_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_log_notes_id'), table_name='work_log_notes')
    op.drop_table('work_log_notes')
    op.drop_index(op.f('ix_setup_info_id'), table_name='setup_info')
    op.drop_table('setup_info')
    op.drop_index(op.f('ix_operation_details_id'), table_name='operation_details')
    op.drop_table('operation_details')
    op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index(op.f('ix_order_drawings_order_id'), table_name='order_drawings')
    op.drop_index(op.f('ix_order_drawings_id'), table_name='order_drawings')
    op.drop_table('order_drawings')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_drawings_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_hash'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_archived_work_logs_id'), table_name='archived_work_logs')
    op.drop_table('archived_work_logs')
    op.drop_index(op.f('ix_archived_production_orders_order_number'), table_name='archived_production_orders')
    op.drop_index(op.f('ix_archived_production_orders_id'), table_name='archived_production_orders')
    op.drop_table('archived_production_orders')
    # ### end Alembic commands ###
