"""Auto-generated migration 20240826_134650

Revision ID: d220eaa27e41
Revises: 5edde1a1056e
Create Date: 2024-08-26 13:46:50.743434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd220eaa27e41'
down_revision: Union[str, None] = '5edde1a1056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
