"""Auto-generated migration 20240806_133304

Revision ID: d4ede09ac124
Revises: 8cb7c43eea97
Create Date: 2024-08-06 13:33:04.582985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ede09ac124'
down_revision: Union[str, None] = '8cb7c43eea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
