"""Auto-generated migration 20241129_094933

Revision ID: d606e4cb2d55
Revises: 36f20320985f
Create Date: 2024-11-29 09:49:34.077415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd606e4cb2d55'
down_revision: Union[str, None] = '36f20320985f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
