"""Auto-generated migration 20240903_142734

Revision ID: d61c32f755e0
Revises: 4559c1dca8a2
Create Date: 2024-09-03 14:27:34.564153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61c32f755e0'
down_revision: Union[str, None] = '4559c1dca8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
