"""Auto-generated migration 20241211_124334

Revision ID: dbfc8a4a2464
Revises: d606e4cb2d55
Create Date: 2024-12-11 12:43:35.855441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfc8a4a2464'
down_revision: Union[str, None] = 'd606e4cb2d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
