"""Auto-generated migration 20241108_131345

Revision ID: dca28236e586
Revises: e976c5eabf7b
Create Date: 2024-11-08 13:13:46.173144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca28236e586'
down_revision: Union[str, None] = 'e976c5eabf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
