"""Добавил больше безопасности для токенов

Revision ID: dea361cf801e
Revises: 9b35c30f62c0
Create Date: 2024-10-22 13:53:33.547796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea361cf801e'
down_revision: Union[str, None] = '9b35c30f62c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('lock_expiry', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'last_failed_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_failed_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'lock_expiry')
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###
