"""Auto-generated migration 20241008_142902

Revision ID: e071d0338bcd
Revises: 12af1d58cf47
Create Date: 2024-10-08 14:29:02.797033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e071d0338bcd'
down_revision: Union[str, None] = '12af1d58cf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
