"""Добавил индексы для revoked_tokens

Revision ID: e1fe9b1034a6
Revises: 6197ed1527f9
Create Date: 2024-11-01 14:34:02.087121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fe9b1034a6'
down_revision: Union[str, None] = '6197ed1527f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_index('ix_revoked_tokens_token_type', 'revoked_tokens', ['token_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revoked_tokens_token_type', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    # ### end Alembic commands ###
