"""Auto-generated migration 20240919_144107

Revision ID: e4546cb6da2b
Revises: 65a677c50224
Create Date: 2024-09-19 14:41:07.495552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4546cb6da2b'
down_revision: Union[str, None] = '65a677c50224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
