"""Auto-generated migration 20240903_144220

Revision ID: e74882612e1e
Revises: d61c32f755e0
Create Date: 2024-09-03 14:42:21.049511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74882612e1e'
down_revision: Union[str, None] = 'd61c32f755e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
