"""Auto-generated migration 20241007_114221

Revision ID: e84b2e530c8e
Revises: 79af3bfd43af
Create Date: 2024-10-07 11:42:22.342243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84b2e530c8e'
down_revision: Union[str, None] = '79af3bfd43af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
