"""Auto-generated migration 20240905_122817

Revision ID: ea2cd6f80cdb
Revises: cd11aac03823
Create Date: 2024-09-05 12:28:17.651332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2cd6f80cdb'
down_revision: Union[str, None] = 'cd11aac03823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
