"""Auto-generated migration 20241031_134415

Revision ID: ec035c64b69b
Revises: f44927bdcaee
Create Date: 2024-10-31 13:44:16.283660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec035c64b69b'
down_revision: Union[str, None] = 'f44927bdcaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
