"""Current database state

Revision ID: ec470764dcb9
Revises: 1c3f4c2fa58f
Create Date: 2024-08-30 13:43:24.460082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec470764dcb9'
down_revision: Union[str, None] = '1c3f4c2fa58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_drawings_hash', table_name='drawings')
    op.drop_index('idx_order_drawings_order_id', table_name='order_drawings')
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'required_material',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'desired_production_date_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_orders', 'drawing_designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_orders', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index('idx_order_drawings_order_id', 'order_drawings', ['order_id'], unique=False)
    op.create_index('idx_drawings_hash', 'drawings', ['hash'], unique=False)
    # ### end Alembic commands ###
