"""Auto-generated migration 20240917_093741

Revision ID: f2cb2c1d2206
Revises: 59cfca4d9374
Create Date: 2024-09-17 09:37:41.748288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cb2c1d2206'
down_revision: Union[str, None] = '59cfca4d9374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
