"""Auto-generated migration 20241009_105723

Revision ID: f30ddc4ccd6d
Revises: 0d0eeb0e2a8f
Create Date: 2024-10-09 10:57:23.777040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30ddc4ccd6d'
down_revision: Union[str, None] = '0d0eeb0e2a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
