"""Добавление чертежа к новому заказу не обязательное

Revision ID: f4f2d27bab51
Revises: 55a3979542ce
Create Date: 2024-10-23 13:49:03.709590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f2d27bab51'
down_revision: Union[str, None] = '55a3979542ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
