"""Добавил таблицу отозванных токенов

Revision ID: f7888e2677da
Revises: a536411a9f46
Create Date: 2024-10-22 14:28:17.442455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7888e2677da'
down_revision: Union[str, None] = 'a536411a9f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('idx_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index('idx_session_token_type', 'revoked_tokens', ['session_id', 'token_type'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=45), nullable=False))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_sessions', sa.Column('access_token_jti', sa.String(length=36), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_token_jti', sa.String(length=36), nullable=True))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_sessions_token_key', 'user_sessions', type_='unique')
    op.create_unique_constraint(None, 'user_sessions', ['access_token_jti'])
    op.create_unique_constraint(None, 'user_sessions', ['refresh_token_jti'])
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.create_unique_constraint('user_sessions_token_key', 'user_sessions', ['token'])
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_sessions', 'refresh_token_jti')
    op.drop_column('user_sessions', 'access_token_jti')
    op.drop_column('user_sessions', 'is_active')
    op.drop_column('user_sessions', 'last_activity')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'ip_address')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_index('idx_session_token_type', table_name='revoked_tokens')
    op.drop_index('idx_expires_at', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
