"""Auto-generated migration 20240812_123435

Revision ID: f996dbc7d541
Revises: fa1d7c90ab5f
Create Date: 2024-08-12 12:34:36.109823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f996dbc7d541'
down_revision: Union[str, None] = 'fa1d7c90ab5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
