"""Auto-generated migration 20240809_151007

Revision ID: fa1d7c90ab5f
Revises: 9fa948a11d3d
Create Date: 2024-08-09 15:10:08.005259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1d7c90ab5f'
down_revision: Union[str, None] = '9fa948a11d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
