"""Auto-generated migration 20241007_101423

Revision ID: fb0c7b85c22a
Revises: d04a625f395c
Create Date: 2024-10-07 10:14:24.126433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0c7b85c22a'
down_revision: Union[str, None] = 'd04a625f395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_work_logs', sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift'), nullable=False))
    op.add_column('work_logs', sa.Column('shift', sa.Enum('DAY', 'NIGHT', name='shift'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_logs', 'shift')
    op.drop_column('archived_work_logs', 'shift')
    # ### end Alembic commands ###
