"""Auto-generated migration 20240827_124446

Revision ID: fb54935d2e19
Revises: 6ba2140a5f98
Create Date: 2024-08-27 12:44:47.083935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb54935d2e19'
down_revision: Union[str, None] = '6ba2140a5f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
