"""Auto-generated migration 20240826_133254

Revision ID: fe3b12be5343
Revises: aa5d7a8933ea
Create Date: 2024-08-26 13:32:55.032451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3b12be5343'
down_revision: Union[str, None] = 'aa5d7a8933ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
