"""Initial migration

Revision ID: ffd5b2c05e6b
Revises: 
Create Date: 2024-07-18 12:44:02.871397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd5b2c05e6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batch_number'), 'inventory', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_part_number'), 'inventory', ['part_number'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=6), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('drawing_designation', sa.String(), nullable=False),
    sa.Column('drawing_link', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('desired_production_date_start', sa.Date(), nullable=False),
    sa.Column('desired_production_date_end', sa.Date(), nullable=False),
    sa.Column('required_material', sa.String(), nullable=False),
    sa.Column('metal_delivery_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.drop_table('part')
    op.drop_index('ix_batches_id', table_name='batches')
    op.drop_table('batches')
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('requests')
    op.drop_index('ix_items_batch_number', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_part_number', table_name='items')
    op.drop_table('items')
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('request_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('request_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('drawing', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('approved_manufacturing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='request_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('part_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_part_number', 'items', ['part_number'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_batch_number', 'items', ['batch_number'], unique=False)
    op.create_table('requests',
    sa.Column('request_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drawing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('approved_manufacturing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('blank', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material_delivery_deadline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('request_number', name='requests_pkey')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('part_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='batches_pkey')
    )
    op.create_index('ix_batches_id', 'batches', ['id'], unique=False)
    op.create_table('part',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blank', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('material_delivery_deadline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name='part_request_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='part_pkey')
    )
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_inventory_part_number'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_batch_number'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
